name: Build qtbase-abi-5-15-10

on:
  workflow_dispatch

jobs:
  build:
    runs-on: debian:sid
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
  
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    
    - name: Build Package
      run: ./qtbase-abi-5-15-10.sh
